export const FETCHED_CATEGORIES = "FETCHED_CATEGORIES";
export const GET_ERRORS = "GET_ERRORS";
export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
export const DELETED_ENTITY = "DELETED_ENTITY";
export const CREATED_ENTITY = "CREATED_ENTITY";
export const UPDATED_ENTITY = "UPDATED_ENTITY";